---
- name: Deploy NTP configuration
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - Restart NTP

  handlers:
    - name: Restart NTP
      service:
        name: ntpd
        state: restarted

